//! This code was generated by `zbus-xmlgen` `4.1.0` from DBus introspection data.
//!
//! By running `zbus-xmlgen system de.pengutronix.rauc /` on the LXA TAC.

use zbus::proxy;

#[proxy(
    interface = "de.pengutronix.rauc.Installer",
    default_service = "de.pengutronix.rauc",
    default_path = "/"
)]
pub trait Installer {
    /// GetPrimary method
    fn get_primary(&self) -> zbus::Result<String>;

    /// GetSlotStatus method
    fn get_slot_status(
        &self,
    ) -> zbus::Result<
        Vec<(
            String,
            std::collections::HashMap<String, zbus::zvariant::OwnedValue>,
        )>,
    >;

    /// Info method
    fn info(&self, bundle: &str) -> zbus::Result<(String, String)>;

    /// InspectBundle method
    fn inspect_bundle(
        &self,
        source: &str,
        args: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// Install method
    fn install(&self, source: &str) -> zbus::Result<()>;

    /// InstallBundle method
    fn install_bundle(
        &self,
        source: &str,
        args: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// Mark method
    fn mark(&self, state: &str, slot_identifier: &str) -> zbus::Result<(String, String)>;

    /// Completed signal
    #[zbus(signal)]
    fn completed(&self, result: i32) -> zbus::Result<()>;

    /// BootSlot property
    #[zbus(property)]
    fn boot_slot(&self) -> zbus::Result<String>;

    /// Compatible property
    #[zbus(property)]
    fn compatible(&self) -> zbus::Result<String>;

    /// LastError property
    #[zbus(property)]
    fn last_error(&self) -> zbus::Result<String>;

    /// Operation property
    #[zbus(property)]
    fn operation(&self) -> zbus::Result<String>;

    /// Progress property
    #[zbus(property)]
    fn progress(&self) -> zbus::Result<(i32, String, i32)>;

    /// Variant property
    #[zbus(property)]
    fn variant(&self) -> zbus::Result<String>;
}
